python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  9606 &	# "homo sapiens[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  10090 &	# "mus musculus[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  10114 &	# "Rattus[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  3702 &	# "arabidopsis thaliana[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  562 &	# "escherichia coli[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  7227 &	# "drosophila melanogaster[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  287 &	# "pseudomonas aeruginosa[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  4932 &	# "saccharomyces cerevisiae[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  7955 &	# "danio rerio[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  44689 &	# "dictyostelium discoideum[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  2097 &	# "Mycoplasma genitalium[All Names]"
python filter_sp_species.py /home/idoerg/work/CAFA3/uniprot_sprot.dat  6239 &	# "caenorhabditis elegans[All Names]"
