bp_taxid4species "Homo Sapiens"
bp_taxid4species "Mus musculus"
bp_taxid4species "Rattus"
bp_taxid4species "Arabidopsis thaliana"
bp_taxid4species "Escherichia coli"
bp_taxid4species "Drosophila melanogaster"
bp_taxid4species "Pseudomonas aeruginosa"
bp_taxid4species "Saccharomyces cerevisiae"
bp_taxid4species "Danio rerio"
bp_taxid4species "Dictyostelium discoideum"
bp_taxid4species "Mycoplasma genitalium"
bp_taxid4species "Caenorhabditis elegans"
